apiVersion: skaffold/v1beta7
kind: Config
build:
  artifacts:
  - image: sample-app-api
    context: .
    docker: {}
  tagPolicy:
    sha256: {}
  local: {}
deploy:
  helm:
    releases:
    - name: sample-app-api
      chartPath: charts/springboot-local
      values:
        image.name: sample-app-api
        image.repository: sample-app-api
