apiVersion: skaffold/v1beta7
kind: Config
build:
  artifacts:
  - image: sample-app-api
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: "{{ .DOCKER_REGISTRY }}/myproject/{{ .IMAGE_NAME }}"
  local: {}
deploy:
  helm:
    releases:
    - name: sample-app-api
      namespace: myproject
      chartPath: charts/springboot-local
      setValueTemplates:
        image.repository: '{{ .DOCKER_REGISTRY }}/myproject/{{ .IMAGE_NAME }}'
