apiVersion: skaffold/v1beta7
kind: Config
build:
  artifacts:
  - image: 172.30.1.1:5000/myproject/sample-app-api
    context: .
    docker: {}
  tagPolicy:
    sha256: {}
  local: {}
deploy:
  helm:
    releases:
    - name: sample-app-api
      namespace: myproject
      chartPath: charts/springboot-local
      values:
        image.repository: 172.30.1.1:5000/myproject/sample-app-api
